"""
Coder Service API routes for skill management.
"""

import logging
from typing import Any

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

logger = logging.getLogger("coder.api.skills")

router = APIRouter(prefix="/api/v1/skills", tags=["skills"])


# Request/Response models
class CreateSkillRequest(BaseModel):
    """Request to create a new skill"""

    name: str = Field(..., description="Skill name")
    description: str = Field(..., description="What the skill does")
    category: str = Field(..., description="Skill category")
    input_schema: dict[str, Any] = Field(default_factory=dict, description="Input schema")
    output_schema: dict[str, Any] = Field(default_factory=dict, description="Output schema")


class ImproveSkillRequest(BaseModel):
    """Request to improve an existing skill"""

    skill_name: str = Field(..., description="Name of skill to improve")
    feedback: str = Field(..., description="Feedback for improvement")
    test_results: dict[str, Any] = Field(default_factory=dict, description="Test results")


class SkillResponse(BaseModel):
    """Response for skill operation"""

    skill_id: str
    name: str
    status: str
    description: str = ""
    category: str = ""


@router.post("/generate")
async def generate_skill(request: CreateSkillRequest) -> dict:
    """
    Generate a new skill from description.

    Args:
        request: Skill creation request

    Returns:
        Generated skill details
    """
    import main as coder_main

    if not coder_main.coder_agent:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Coder Agent not initialized",
        )

    try:
        result = await coder_main.coder_agent.create_skill(
            name=request.name,
            description=request.description,
            category=request.category,
            input_schema=request.input_schema,
            output_schema=request.output_schema,
        )

        return result

    except Exception as e:
        logger.error(f"Skill generation failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Skill generation failed: {str(e)}",
        ) from e


@router.post("/improve")
async def improve_skill(request: ImproveSkillRequest) -> dict:
    """
    Improve an existing skill based on feedback.

    Args:
        request: Skill improvement request

    Returns:
        Improved skill details
    """
    import main as coder_main

    if not coder_main.coder_agent:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Coder Agent not initialized",
        )

    try:
        result = await coder_main.coder_agent.improve_skill(
            skill_name=request.skill_name,
            feedback=request.feedback,
            test_results=request.test_results,
        )

        return result

    except Exception as e:
        logger.error(f"Skill improvement failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Skill improvement failed: {str(e)}",
        ) from e


@router.get("/generated")
async def get_generated_skills() -> dict:
    """
    Get all skills generated by Coder Agent.

    Returns:
        List of generated skills
    """
    import main as coder_main

    if not coder_main.coder_agent:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Coder Agent not initialized",
        )

    skills = await coder_main.coder_agent.get_generated_skills()

    return {
        "total": len(skills),
        "skills": [
            {
                "skill_id": s["skill_id"],
                "name": s["name"],
                "category": s["category"],
                "status": s["status"],
                "created_at": s["created_at"],
                "code_lines": len(s["code"].split("\n")),
                "test_cases": len(s["tests"]),
            }
            for s in skills
        ],
    }


@router.get("/{skill_id}/status")
async def get_skill_status(skill_id: str) -> dict:
    """
    Get status of a generated skill.

    Args:
        skill_id: Skill ID

    Returns:
        Skill status details
    """
    import main as coder_main

    if not coder_main.coder_agent:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Coder Agent not initialized",
        )

    skill_status = await coder_main.coder_agent.get_skill_status(skill_id)

    if skill_status.get("status") == "not_found":
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Skill {skill_id} not found",
        )

    return skill_status
