#!/bin/bash

# Demo: Show how multiple environments work simultaneously
# Usage: ./scripts/demo_multi_env.sh

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "   🎭 Multi-Environment Demo - Run All 3 Simultaneously!"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📖 Scenario: Developer working on new feature"
echo ""
echo "This demo shows how to run Dev, Test, and Prod at the same time"
echo "on ONE server without any conflicts!"
echo ""

read -p "Press Enter to continue..."

# Show current status
echo ""
echo "Step 1: Current system status"
echo "────────────────────────────────────────────────────────────"
./scripts/status_all_envs.sh

read -p "Press Enter to start Development environment..."

# Start Dev
echo ""
echo "Step 2: Starting DEVELOPMENT environment"
echo "────────────────────────────────────────────────────────────"
echo "Command: ./scripts/start_dev.sh"
echo ""
echo "What happens:"
echo "  • Loads .env.dev configuration"
echo "  • Starts services on ports 8100-8200"
echo "  • Uses database: balbes_dev"
echo "  • Enables hot reload for development"
echo ""
read -p "Press Enter to continue..."

# Show dev commands
echo ""
echo "Step 3: Development workflow"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Now you can develop:"
echo ""
echo "  Terminal 1 (Dev services):"
echo "    $ ./scripts/start_dev.sh"
echo "    ✅ Services running on 8100-8200"
echo ""
echo "  Terminal 2 (Frontend):"
echo "    $ cd web-frontend && npm run dev"
echo "    ✅ Frontend on http://localhost:5173"
echo ""
echo "  Terminal 3 (Coding):"
echo "    $ vim services/memory-service/api/new_feature.py"
echo "    ✅ Auto-reload works!"
echo ""
read -p "Press Enter to start Testing environment..."

# Start Test
echo ""
echo "Step 4: Starting TESTING environment"
echo "────────────────────────────────────────────────────────────"
echo "Command: ./scripts/start_test.sh"
echo ""
echo "What happens:"
echo "  • Loads .env.test configuration"
echo "  • Starts services on ports 9100-9200 (different!)"
echo "  • Uses database: balbes_test (separate!)"
echo "  • Uses tmpfs (memory) for speed and auto-cleanup"
echo ""
echo "Dev still running on 8100-8200! ✅"
echo "Test now running on 9100-9200! ✅"
echo "NO CONFLICTS! ✨"
echo ""
read -p "Press Enter to show test commands..."

# Show test commands
echo ""
echo "Step 5: Testing workflow"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "  Terminal 4 (Tests):"
echo "    $ ./scripts/start_test.sh"
echo "    $ ENV=test pytest tests/test_e2e.py -v"
echo "    ✅ Tests run on 9100-9200"
echo ""
echo "    $ ./scripts/stop_test.sh"
echo "    ✅ Auto-cleanup (tmpfs erased)"
echo ""
echo "Dev STILL running on 8100-8200! No interruption!"
echo ""
read -p "Press Enter to see production setup..."

# Show prod
echo ""
echo "Step 6: Production environment"
echo "────────────────────────────────────────────────────────────"
echo "Command: ./scripts/start_prod.sh"
echo ""
echo "What happens:"
echo "  • Checks for secure passwords (fails if CHANGE_ME)"
echo "  • Starts in isolated Docker network"
echo "  • Uses persistent volumes"
echo "  • Runs with multiple workers (2-4)"
echo "  • Monitored by systemd (optional)"
echo ""
echo "Can run alongside Dev/Test if using Docker network isolation!"
echo ""
read -p "Press Enter to see final summary..."

# Final summary
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "   ✨ Multi-Environment Solution Summary"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "┌───────────────┬──────────────┬─────────────┬──────────────┐"
echo "│ Environment   │ Ports        │ Database    │ Use Case     │"
echo "├───────────────┼──────────────┼─────────────┼──────────────┤"
echo "│ 🟦 Dev        │ 8100-8200    │ balbes_dev  │ Development  │"
echo "│ 🟨 Test       │ 9100-9200    │ balbes_test │ Auto tests   │"
echo "│ 🟩 Prod       │ 8100-8200    │ balbes      │ Production   │"
echo "└───────────────┴──────────────┴─────────────┴──────────────┘"
echo ""
echo "✅ Benefits:"
echo "   • Full isolation (ports, DBs, data)"
echo "   • Run all 3 simultaneously"
echo "   • No conflicts"
echo "   • Simple commands"
echo ""
echo "🎯 Commands:"
echo "   ./scripts/start_dev.sh    - Start development"
echo "   ./scripts/start_test.sh   - Start testing"
echo "   ./scripts/start_prod.sh   - Start production"
echo ""
echo "📊 Status:"
echo "   ./scripts/status_all_envs.sh - Check all environments"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎉 Problem solved! You can now develop, test, and run"
echo "   production on the SAME server without conflicts!"
echo ""
